### ISSUE TITLE
Using Multiple OLEDs

### ISSUE THREAD

**Issue by equalunique** [mtei/qmk_firmware#7]
Hi mtei,

I saw your interesting tests for OLEDs on Helix in this QMK issue: https://github.com/qmk/qmk_firmware/issues/4254#issuecomment-446672246

Recently I found someone who came up with another technique for combining multiple OLEDs with the same I2C address: http://bitbanksoftware.blogspot.com/2019/01/controlling-lots-of-oled-displays-with.html

Perhaps maybe if you still have your test setup, you could try that technique & see how well it works.

**Comment by mtei** [comment]
Thank you for letting me know that. I haven't read the details yet, but the article is very interesting.

**Comment by drashna** [comment]
Also, I've looked. There are OLEDs that are about this size that do have configurable i2c addresses.  But I'm sure they're more expensive, and harder to source.

**Comment by drashna** [comment]
I wasn't really sure how to contact you, @mtei but .... the OLED driver from @XScorpion2 (linked above) works very well on the crkbd, and I'm sure on the helix too.  It also has the option to rotate the screen 90 degrees.   

![image](https://user-images.githubusercontent.com/2584963/55689061-1f9c8180-5935-11e9-9828-ed7e197759e3.png)

Also, I don't know about the helix code, but the crkbd, it runs the OLED on both halves... and I was able to get this: 
![image](https://user-images.githubusercontent.com/2584963/55689069-38a53280-5935-11e9-916b-53b41cbbc535.png)
Notice that there is no USB connection on that side (I only have one working OLED screen). 

I figured it was worth showing this to you, since it is pretty awesome! And it compiles smaller.

https://github.com/drashna/qmk_firmware/blob/custom_drashna/keyboards/crkbd/keymaps/drashna/keymap.c#L296-L393
